#! /bin/sh

bspc config border_width                1
bspc config window_gap			23
bspc config split_ratio                 0.50
bspc config left_padding		0
bspc config right_padding		0
bspc config bottom_padding		0
bspc config top_padding 		15
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config focus_follows_pointer       false
bspc config click_to_focus true
bspc config pointer_modifier mod4

bspc config auto_alternate              false
bspc config auto_cancel                 true
bspc config top_padding                 24
bspc config normal_border_color         "#181512"
bspc config focused_border_color        "#A9A2A2"
bspc config presel_border_color         "#AC4142"

bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.05

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config click_to_focus true
bspc config pointer_modifier mod1


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
